### ISSUE TITLE
please add the provider verimi

### ISSUE THREAD

**Issue by rallek** [zikula/OAuth#5]
https://www.verimi.de/
https://www.verimi.de/en/

This becomes an european standard

Here some documentation: https://www.verimi.de/sandbox/html/sdk.html

**Comment by craigh** [comment]
OAuth will not be expanded beyond existing providers. You will need to code your own.

**Comment by rallek** [comment]
So only American providers are used and European possibilities are ignored.

I am not a coder and do need help to code my own solution.

**Comment by craigh** [comment]
guilt is not an effective motivator.

I would hard call Facebook, Github, Google and LinkedIn strictly American providers. Especially since you _USING GITHUB_ to complain. Perhaps they are American companies, but they are international solutions. You are requesting a European-only solution.

consider paying someone. I don't work for you.

**Comment by Guite** [comment]
> This becomes an european standard

Verimi had a bad start.

New player: https://enid.foundation/
